/*
 * This source file was generated by the Gradle 'init' task
 */
package swingui_01;

import java.awt.Color;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

import com.swingui.constant.UIAlignmentX;
import com.swingui.constant.UIAlignmentY;
import com.swingui.constant.UIDefaults;
import com.swingui.front.Frame;
import com.swingui.front.layout.HStack;
import com.swingui.front.layout.VStack;
import com.swingui.value.UIValue;

public class Startup
{
    public static void main(String[] args)
    {
        new Startup();
    }

    public Startup()
    {
        SwingUtilities.invokeLater(() -> buildUpInVertical());
        SwingUtilities.invokeLater(() -> buildUpInHorizontal());
    }

    /**
     * 垂直レイアウト（内部に水平レイアウト）で画面構築する。
     */
    private void buildUpInVertical()
    {
        Frame.of
        (
            "SwingUI Layout Sample",

            (f) ->
            {
                f.setResizable(true);    // 画面リサイズ可能
                f.setSize(400, 300); // 初期画面サイズ指定
            },

            VStack.of
            (
                UIAlignmentX.Center,

                text("TOP"),

                HStack.of
                (
                    text("LEFT"),
                    text("CENTER"),
                    text("RIGHT")
                )
                .padding(UIDefaults.COMPONENT_GAP)
                .background(UIValue.of(Color.yellow)),

                text("BOTTOM")
            )
            .frame(400, 300)
            .padding(UIDefaults.COMPONENT_GAP)
            .background(UIValue.of(Color.cyan))
        );
    }

    /**
     * 水平レイアウト（内部に垂直レイアウト）で画面構築する。
     */
    private void buildUpInHorizontal()
    {
        Frame.of
        (
            "SwingUI Layout Sample",

            (f) ->
            {
                f.setResizable(true);    // 画面リサイズ可能
                f.setSize(400, 300); // 初期画面サイズ指定
            },

            HStack.of
            (
                UIAlignmentY.Center,

                text("LEFT"),

                VStack.of
                (
                    text("TOP"),
                    text("CENTER"),
                    text("BOTTOM")
                )
                .padding(UIDefaults.COMPONENT_GAP)
                .background(UIValue.of(Color.cyan)),

                text("RIGHT")
            )
            .frame(400, 300)
            .padding(UIDefaults.COMPONENT_GAP)
            .background(UIValue.of(Color.yellow))
        );
    }

    /**
     * ラベルを生成する。
     * 
     * @param text ラベル文字列
     * @return {@link JLabel}
     */
    private JLabel text(String text)
    {
        JLabel label = new JLabel(text);
        label.setHorizontalAlignment(SwingConstants.CENTER);
        label.setBorder(BorderFactory.createLineBorder(Color.lightGray));
        return label;
    }
}
